<?php
/**
 * Created by PhpStorm.
 * User: YFan
 * Date: 2017/12/23
 * Time: 12:41
 */

namespace backend\models;

//表单模型
use yii\base\Model;

class GoodsSerch extends Model
{
    public $name;//商品名称
    public $sn;//货号
    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
          [['name','sn'],'safe']
        ];
    }
    public function attributeLabels()
    {
        return [
          'name'=>'商品名',
            'sn'=>'货号'
        ];
    }
}